### ISSUE TITLE
Inconsistently -- holochain looking for signal server on localhost

### ISSUE THREAD

**Issue by mattyg** [holochain-apps/holochain-kangaroo#4]
We saw this issue while testing mewsfeed's kanagaroo build:  there was an error in the console that the signal server could not be reached, and the address it was trying to reach was on localhost. 

After restarting the kangaroo app, it properly found the signal server at the expected address.

**Comment by matthme** [comment]
Hmm...can you let me know if you happen to reproduce it? I haven't seen this so far. My guess is that it's rather holochain related than kangaroo related as the signal server URL is just passed to holochain's `ConductorBuilder` so there is no kangaroo specific signaling server logic.

**Comment by mattyg** [comment]
Yeah its holochain -- not actually a problem, just an odd warning from pion: https://github.com/holochain/holochain/issues/2740
